<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return [
    'Tests\\' => [$baseDir . '/tests'],
    'Database\\Seeders\\' => [$baseDir . '/database/seeders'],
    'Database\\Factories\\' => [$baseDir . '/database/factories'],
    'App\\' => [$baseDir . '/app'],
];
