<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit
{
    public static $prefixLengthsPsr4 = [
        'A' => ['App\\' => 4],
        'D' => ['Database\\Seeders\\' => 17, 'Database\\Factories\\' => 19],
        'T' => ['Tests\\' => 6],
    ];

    public static $prefixDirsPsr4 = [
        'App\\' => [__DIR__ . '/../../app'],
        'Database\\Seeders\\' => [__DIR__ . '/../../database/seeders'],
        'Database\\Factories\\' => [__DIR__ . '/../../database/factories'],
        'Tests\\' => [__DIR__ . '/../../tests'],
    ];

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit::$prefixDirsPsr4;
        }, null, ClassLoader::class);
    }
}
